# Generated by Django 4.2.4 on 2023-10-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoods',
            name='neighborhood_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='neighborhoods',
            name='slug',
            field=models.SlugField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='slug',
            field=models.SlugField(max_length=355, unique=True),
        ),
    ]
