# Generated by Django 4.2.4 on 2023-10-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='property_type',
            field=models.CharField(choices=[(None, 'Select house type'), ('Appartment', 'Appartment'), ('Single Family House', 'Single Family House'), ('Condominium', 'Condominium'), ('Townhouse', 'Townhouse'), ('Mobile Home / Manufactured Home', 'Mobile Home / Manufactured Home')], default='', max_length=31),
        ),
    ]
