# Generated by Django 4.2.4 on 2023-10-07 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_propertyinfo_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.AddField(
            model_name='property',
            name='property_description',
            field=models.TextField(default=datetime.datetime(2023, 10, 7, 13, 59, 59, 938432, tzinfo=datetime.timezone.utc), max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='HOA_dues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
