# Generated by Django 4.2.4 on 2023-10-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_neighborhoods_neighborhood_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyaddress',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
