# Generated by Django 4.2.4 on 2023-10-07 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='lease_terms',
            field=models.TextField(default=datetime.datetime(2023, 10, 7, 14, 56, 10, 872107, tzinfo=datetime.timezone.utc), max_length=600),
            preserve_default=False,
        ),
    ]
