# Generated by Django 4.2.4 on 2023-10-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_propertyaddress_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoods',
            name='neighborhood_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='neighborhoods',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
