# Generated by Django 4.2.4 on 2023-10-08 08:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_propertyinfo_lease_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='images',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliances', multiselectfield.db.fields.MultiSelectField(choices=[('Dishwasher', 'Dishwasher'), ('Dryer', 'Dryer'), ('Freezer', 'Freezer'), ('Garbage disposal', 'Garbage disposal'), ('Microwave', 'Microwave'), ('Range / Oven', 'Range / Oven'), ('Refrigerator', 'Refrigerator'), ('Trash compactor', 'Trash compactor'), ('Washer', 'Washer')], default='', max_length=20)),
                ('floor_covering', multiselectfield.db.fields.MultiSelectField(choices=[('Carpet', 'Carpet'), ('Concrete', 'Concrete'), ('Hardwood', 'Hardwood'), ('Laminate', 'Laminate'), ('Slate', 'Slate'), ('Softwood', 'Softwood'), ('Tile', 'Tile'), ('Linoleum / Vinyl', 'Linoleum / Vinyl'), ('Other', 'Other')], default='', max_length=20)),
                ('cooling_type', multiselectfield.db.fields.MultiSelectField(choices=[('Central', 'Central'), ('Evaporative', 'Evaporative'), ('Refrigeration', 'Refrigeration'), ('Geothermal', 'Geothermal'), ('Solar', 'Solar'), ('Wall', 'Wall'), ('Other', 'Other'), ('None', 'None')], default='', max_length=20)),
                ('heating_type', multiselectfield.db.fields.MultiSelectField(choices=[('Electric', 'Electric'), ('Forced air', 'Forced air'), ('Heat pump', 'Heat pump'), ('Geothermal', 'Geothermal'), ('Radiant', 'Radiant'), ('Stove', 'Stove'), ('Gas', 'Gas'), ('Solar', 'Solar'), ('Wall', 'Wall'), ('Other', 'Other')], default='', max_length=20)),
                ('rooms', multiselectfield.db.fields.MultiSelectField(choices=[('Gas', 'Gas'), ('Solar', 'Solar'), ('Gas', 'Gas'), ('Solar', 'Solar'), ('Gas', 'Gas'), ('Solar', 'Solar'), ('Gas', 'Gas'), ('Solar', 'Solar')], default='', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
            ],
        ),
    ]
