# Generated by Django 4.2.4 on 2023-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_propertyamenities_appliances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenities',
            name='appliances',
            field=models.CharField(blank=True, choices=[('Dishwasher', 'Dishwasher'), ('Dryer', 'Dryer'), ('Freezer', 'Freezer'), ('Garbage disposal', 'Garbage disposal'), ('Microwave', 'Microwave'), ('Range / Oven', 'Range / Oven'), ('Refrigerator', 'Refrigerator'), ('Trash compactor', 'Trash compactor'), ('Washer', 'Washer')], default='', max_length=20),
        ),
    ]
