# Generated by Django 4.2.4 on 2023-10-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_propertyamenities_appliances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenities',
            name='appliances',
            field=models.CharField(blank=True, choices=[('Dishwasher', 'Dishwasher'), ('Dryer', 'Dryer'), ('Freezer', 'Freezer'), ('Garbage disposal', 'Garbage disposal'), ('Microwave', 'Microwave'), ('Range / Oven', 'Range / Oven'), ('Refrigerator', 'Refrigerator'), ('Trash compactor', 'Trash compactor'), ('Washer', 'Washer')], max_length=20),
        ),
    ]
