# Generated by Django 4.2.4 on 2023-09-05 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_addpropertygoogle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpropertygoogle',
            name='user',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002503ED0B280>', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
