# Generated by Django 4.2.4 on 2023-10-08 13:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_propertyamenities_appliances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyamenities',
            name='outdoor_amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Balcony / patio', 'Balcony / patio'), ('Barbecue area', 'Barbecue area'), ('Deck', 'Deck'), ('Dock', 'Dock'), ('Renced yard', 'Renced yard'), ('Garden', 'Garden'), ('Greenhouse', 'Greenhouse'), ('Spa / hot tub', 'Spa / hot tub'), ('Lawn', 'Lawn'), ('Pond', 'Pond'), ('Pool', 'Pool'), ('Porch', 'Porch')], default='', max_length=119),
        ),
    ]
