# Generated by Django 4.2.4 on 2023-10-08 14:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_propertyamenities_outdoor_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyamenities',
            name='parking',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Carport', 'Carport'), ('Garage-attached', 'Garage-attached'), ('Garage-detached', 'Garage-detached'), ('Off-street', 'Off-street'), ('On-street', 'On-street'), ('None', 'None')], default='', max_length=72),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='view',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('City', 'City'), ('Mountain', 'Mountain'), ('Park', 'Park'), ('Territorial', 'Territorial'), ('Water', 'Water'), ('None', 'None')], default='', max_length=72),
        ),
        migrations.AlterField(
            model_name='propertyamenities',
            name='outdoor_amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Balcony / patio', 'Balcony / patio'), ('Barbecue area', 'Barbecue area'), ('Deck', 'Deck'), ('Dock', 'Dock'), ('Fenced yard', 'Fenced yard'), ('Garden', 'Garden'), ('Greenhouse', 'Greenhouse'), ('Spa / hot tub', 'Spa / hot tub'), ('Lawn', 'Lawn'), ('Pond', 'Pond'), ('Pool', 'Pool'), ('Porch', 'Porch')], default='', max_length=119),
        ),
    ]
