# Generated by Django 4.2.4 on 2023-09-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_addpropertygoogle_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpropertygoogle',
            name='property_type',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('Single Family House', 'Single Family House'), ('Condominium', 'Condominium'), ('Townhouse', 'Townhouse'), ('Mobile Home/ Manufactured Home', 'Mobile Home/ Manufactured Home')], default='', max_length=30),
        ),
    ]
