# Generated by Django 4.2.4 on 2023-10-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_propertyamenities_parking_propertyamenities_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAddUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms_unit', models.CharField(choices=[(None, 'Select bedrooms'), ('Studio', 'Studio'), ('1 bed', '1 bed'), ('2 bed', '2 bed'), ('3 bed', '3 bed'), ('4 bed+', '4 bed+')], default='', max_length=6)),
                ('bathrooms_unit', models.CharField(choices=[(None, 'Select bathrooms'), ('1 bath', '1 bath'), ('1.5 bath', '1.5 bath'), ('2 bath', '2 bath'), ('2.5 bath', '2.5 bath'), ('3 bath', '3 bath'), ('3.5 bath', '3.5 bath'), ('4 bath+', '4 bath+')], default='', max_length=8)),
                ('square_footage_unit', models.PositiveIntegerField()),
                ('price_unit', models.PositiveIntegerField()),
                ('image_unit', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
            ],
        ),
    ]
