# Generated by Django 4.2.4 on 2023-10-08 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_propertyaddunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyaddunit',
            name='title_unit',
            field=models.CharField(default=datetime.datetime(2023, 10, 8, 19, 51, 48, 857275, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
