# Generated by Django 4.2.4 on 2023-10-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_propertyaddunit_title_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyaddunit',
            name='bathrooms_unit',
            field=models.CharField(blank=True, choices=[(None, 'Select bathrooms'), ('1 bath', '1 bath'), ('1.5 bath', '1.5 bath'), ('2 bath', '2 bath'), ('2.5 bath', '2.5 bath'), ('3 bath', '3 bath'), ('3.5 bath', '3.5 bath'), ('4 bath+', '4 bath+')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='propertyaddunit',
            name='bedrooms_unit',
            field=models.CharField(blank=True, choices=[(None, 'Select bedrooms'), ('Studio', 'Studio'), ('1 bed', '1 bed'), ('2 bed', '2 bed'), ('3 bed', '3 bed'), ('4 bed+', '4 bed+')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='propertyaddunit',
            name='image_unit',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='propertyaddunit',
            name='price_unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyaddunit',
            name='square_footage_unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyaddunit',
            name='title_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
