# Generated by Django 4.2.4 on 2023-10-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_propertyaddunit_bathrooms_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='lease_terms',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
