# Generated by Django 4.2.4 on 2023-10-12 07:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_propertyinfo_lease_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyamenities',
            name='pets',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('No pets allowed', 'No pets allowed'), ('Cats allowed', 'Cats allowed'), ('Dogs allowed', 'Dogs allowed')], default='', max_length=72),
        ),
    ]
